name: My First CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lanshan/suyou:6.6
    - name: Login in 
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Image
      run: docker push lanshan/suyou:6.6
      
      
      
      
      
      
      
      
      
